### PR TITLE
Some design discussion documentation from Hacker News thread and blog…

### PR DESCRIPTION
**Pull request by virtualirfan**
Directional, not fully polished.

### CODE REVIEW

**Comment by ngbinh** [comment]
can you post the link to the thread here too? Thanks

**Comment by virtualirfan** [comment]
[Thread](https://news.ycombinator.com/item?id=10181051) and the [blog post](https://www.bionicspirit.com/blog/2015/09/06/monifu-vs-akka-streams.html). Do you want it in the markdown or just in the PR for reference?

**Comment by alexandru** [comment]
@virtualirfan, I appreciate that you liked those comments, but problem is my words are Steve-Yegge-style blabber (I've always appreciated Steve Yegge as a writer and ended up borrowing his style). But people with a job to do are not interested in that.

Instead people are interested in some quick samples to get a feel of what the library is about, plus people really suffer from attention deficit, so the attention span you can rely on is measured in seconds. People interested in Monifu's design goals and ideas should follow a link instead. We can probably take these opinions, maybe distill them into something that feels less defensive/aggressive and put them on our (outdated and in need of an update) Wiki. 

In the README I think that what's needed would be a better code sample that showcases its utility better. And if you think there are ideas of what I said that should appear in the README, lets cleanup and introduce bullet points in that "Highlights" list.

Note - I really appreciate this PR. This project badly needs documentation. The only thing that's fairly up to date is the [API documentation](https://monifu.org/api/current/). I intend to (re)write the articles in the Wiki to make them up to date, plus I was intending to start writing a series of articles in the Wiki concentrating on tricks and design patterns. If you're interested in getting involved, there's plenty of documentation to write (this besides actual development of features you want, of which I'll gladly take pull requests, but documentation is a good way to get started :-P).

So what do you think?

**Comment by virtualirfan** [comment]
@alexandru Just be specific on your review comments and I'll make the changes. OK?

**Pull request closed without merging**
